development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: mor_development
  pool: 5

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: more_test
  pool: 5